spring:
  application:
    name: eureka-client
  datasource: 
        name: test 
        url: jdbc:mysql://127.0.0.1:3306/drj 
        username: root 
        password: 199458 # 使用druid数据源 
        driver-class-name: com.mysql.jdbc.Driver
server:
  host: localhost
  port: 8890
eureka:
  client:
    #此项目不作为客户端注册
    #register-with-eureka: false
    #fetch-registry: false
    service-url:
      #开启权限验证后Eureka地址为 用户名：密码@地址：端口号，如未开启权限验证则直接使用 地址：端口号
      defaultZone: http://localhost:8888/eureka
